version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 4
    labels:
      - dependabot
    commit-message:
      prefix: chore
  - package-ecosystem: npm
    directory: /example
    schedule:
      interval: weekly
    open-pull-requests-limit: 2
    labels:
      - dependabot
    commit-message:
      prefix: chore
  - package-ecosystem: npm
    directory: /plugin
    schedule:
      interval: weekly
    open-pull-requests-limit: 2
    labels:
      - dependabot
    commit-message:
      prefix: chore
